version: "3.9"
services:
  backend:
    build: .
    container_name: backend-todo
    command: python manage.py runserver 0.0.0.0:5050
    volumes:
      - ./core:/app
    ports:
      - "5050:5050"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
