# Generated by Django 3.2.23 on 2023-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
